import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [data, setdata] = useState([]);
  const getData = async () => {
    try {
      const res = await axios({
        method: "GET",
        url: "https://www.koimoi.com/wp-json/wp/v2/posts",
      });

      if (res && res.data) {
        setdata(res.data);
      }
      console.log("res+++", res);
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    getData();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Test Data Scaper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>test</main>
      {data.map((value: any) => {
        return (
          <>
            <div
              key={value.id}
              dangerouslySetInnerHTML={{ __html: value.content.rendered }}
            ></div>
          </>
        );
      })}
    </div>
  );
};

export default Home;
